package com.xworkz.interfaces.runner;

import com.xworkz.interfaces.external.*;
import com.xworkz.interfaces.internal.rules.*;

public class Runner {
    public static void main(String[] args) {
        Hospital hospital=new GovtHospital();
        hospital.treatment();
        GovtHospital govtHospital=new GovtHospital();
        govtHospital.treatment();
        Furniture furniture=new Chair();
        furniture.use();
        Chair chair=new Chair();
        chair.use();
        Book book=new Fairytale() ;
        book.author();
        Fairytale fairytale=new Fairytale();
        fairytale.author();
        Pencil pencil=new Nataraj() ;
        pencil.use();
        Nataraj nataraj = new Nataraj();
        nataraj.use();
        Cup cup =new PaperCup();
        cup.display();
        cup.shape();
        cup.use();
        PaperCup paperCup=new PaperCup();
        paperCup.display();
        paperCup.use();
        paperCup.shape();
        School school=new Kvg();
        school.learn();
        school.play();
        school.teach();
        Kvg kvg=new Kvg();
        kvg.learn();
        kvg.play();
        kvg.teach();
        Internship internship=new Xworkz();
        internship.learn();
        internship.attend();
        internship.teach();
        Xworkz xworkz=new Xworkz();
        xworkz.learn();
        xworkz.attend();
        xworkz.teach();
        Fan fan = new CeilingFan();
        fan.turnOn();
        fan.rotate();
        fan.turnOff();

        CeilingFan ceilingFan = new CeilingFan();
        ceilingFan.turnOn();
        ceilingFan.rotate();
        ceilingFan.turnOff();
        Bottle bottle = new WaterBottle();
        bottle.fill();
        bottle.pour();
        bottle.clean();

        WaterBottle myBottle = new WaterBottle();
        myBottle.fill();
        myBottle.pour();
        myBottle.clean();
        Light light = new LEDLight();
        light.turnOn();
        light.brighten();
        light.blink();
        light.dim();
        light.turnOff();

        LEDLight led = new LEDLight();
        led.turnOn();
        led.brighten();
        led.blink();
        led.dim();
        led.turnOff();
        Door door = new WoodenDoor();
        door.unlock();
        door.open();
        door.knock();
        door.close();
        door.lock();

        WoodenDoor myDoor = new WoodenDoor();
        myDoor.unlock();
        myDoor.open();
        myDoor.knock();
        myDoor.close();
        myDoor.lock();
        Phone phone = new SmartPhone();
        phone.call();
        phone.text();
        phone.browseInternet();
        phone.takePhoto();
        phone.charge();

        SmartPhone myPhone = new SmartPhone();
        myPhone.call();
        myPhone.text();
        myPhone.browseInternet();
        myPhone.takePhoto();
        myPhone.charge();
        Television tv = new SmartTV();
        tv.turnOn();
        tv.changeChannel();
        tv.adjustVolume();
        tv.displayInfo();
        tv.turnOff();

        SmartTV smart = new SmartTV();
        smart.turnOn();
        smart.changeChannel();
        smart.adjustVolume();
        smart.displayInfo();
        smart.turnOff();
        Car car = new ElectricCar();
        car.start();
        car.accelerate();
        car.brake();
        car.honk();
        car.stop();

        ElectricCar myCar = new ElectricCar();
        myCar.start();
        myCar.accelerate();
        myCar.brake();
        myCar.honk();
        myCar.stop();
        WashingMachine machine = new AutomaticWashingMachine();
        machine.startWash();
        machine.addDetergent();
        machine.spin();
        machine.drainWater();
        machine.setTimer();
        machine.pause();
        machine.stopWash();

        AutomaticWashingMachine myMachine = new AutomaticWashingMachine();
        myMachine.startWash();
        myMachine.addDetergent();
        myMachine.spin();
        myMachine.drainWater();
        myMachine.setTimer();
        myMachine.pause();
        myMachine.stopWash();
        Microwave microwave = new OvenMicrowave();
        microwave.start();
        microwave.heat();
        microwave.defrost();
        microwave.setTimer();
        microwave.openDoor();
        microwave.closeDoor();
        microwave.stop();

        OvenMicrowave myMicrowave = new OvenMicrowave();
        myMicrowave.start();
        myMicrowave.heat();
        myMicrowave.defrost();
        myMicrowave.setTimer();
        myMicrowave.openDoor();
        myMicrowave.closeDoor();
        myMicrowave.stop();
        Robot robot = new HumanoidRobot();
        robot.start();
        robot.walk();
        robot.talk();
        robot.pickUpObject();
        robot.performTask();
        robot.charge();
        robot.stop();

        HumanoidRobot myRobot = new HumanoidRobot();
        myRobot.start();
        myRobot.walk();
        myRobot.talk();
        myRobot.pickUpObject();
        myRobot.performTask();
        myRobot.charge();
        myRobot.stop();
        CoffeeMachine coffeeMachine = new EspressoMachine();
        coffeeMachine.start();
        coffeeMachine.addWater();
        coffeeMachine.addCoffee();
        coffeeMachine.brew();
        coffeeMachine.setTimer();
        coffeeMachine.clean();
        coffeeMachine.stop();

        EspressoMachine myCoffeeMachine = new EspressoMachine();
        myCoffeeMachine.start();
        myCoffeeMachine.addWater();
        myCoffeeMachine.addCoffee();
        myCoffeeMachine.brew();
        myCoffeeMachine.setTimer();
        myCoffeeMachine.clean();
        myCoffeeMachine.stop();
        VendingMachine vendingMachine = new SnackVendingMachine();
        vendingMachine.start();
        vendingMachine.checkStock();
        vendingMachine.acceptPayment();
        vendingMachine.dispenseItem();
        vendingMachine.issueReceipt();
        vendingMachine.refill();
        vendingMachine.stop();

        SnackVendingMachine myVendingMachine = new SnackVendingMachine();
        myVendingMachine.start();
        myVendingMachine.checkStock();
        myVendingMachine.acceptPayment();
        myVendingMachine.dispenseItem();
        myVendingMachine.issueReceipt();
        myVendingMachine.refill();
        myVendingMachine.stop();
        Refrigerator refrigerator = new DoubleDoorRefrigerator();
        refrigerator.turnOn();
        refrigerator.openDoor();
        refrigerator.closeDoor();
        refrigerator.checkPower();
        refrigerator.coolDown();
        refrigerator.defrost();
        refrigerator.clean();
        refrigerator.adjustSettings();
        refrigerator.turnOff();

        DoubleDoorRefrigerator myRefrigerator = new DoubleDoorRefrigerator();
        myRefrigerator.turnOn();
        myRefrigerator.openDoor();
        myRefrigerator.closeDoor();
        myRefrigerator.checkPower();
        myRefrigerator.coolDown();
        myRefrigerator.defrost();
        myRefrigerator.clean();
        myRefrigerator.adjustSettings();
        myRefrigerator.turnOff();
        Elevator elevator = new OfficeElevator();
        elevator.moveUp();
        elevator.openDoor();
        elevator.closeDoor();
        elevator.moveDown();
        elevator.stop();
        elevator.displayFloor();
        elevator.ringAlarm();
        elevator.turnOnLight();
        elevator.turnOffLight();

        OfficeElevator myElevator = new OfficeElevator();
        myElevator.moveUp();
        myElevator.openDoor();
        myElevator.closeDoor();
        myElevator.moveDown();
        myElevator.stop();
        myElevator.displayFloor();
        myElevator.ringAlarm();
        myElevator.turnOnLight();
        myElevator.turnOffLight();
        Printer printer = new InkjetPrinter();
        printer.turnOn();
        printer.connectToWiFi();
        printer.checkInkLevel();
        printer.print();
        printer.scan();
        printer.copy();
        printer.cancelJob();
        printer.cleanNozzles();
        printer.turnOff();

        InkjetPrinter myPrinter = new InkjetPrinter();
        myPrinter.turnOn();
        myPrinter.connectToWiFi();
        myPrinter.checkInkLevel();
        myPrinter.print();
        myPrinter.scan();
        myPrinter.copy();
        myPrinter.cancelJob();
        myPrinter.cleanNozzles();
        myPrinter.turnOff();
        ATM atm = new BankATM();
        atm.displayWelcomeMessage();
        atm.insertCard();
        atm.enterPin();
        atm.checkBalance();
        atm.withdrawCash();
        atm.depositCash();
        atm.printReceipt();
        atm.ejectCard();
        atm.shutdown();

        BankATM bankATM = new BankATM();
        bankATM.displayWelcomeMessage();
        bankATM.insertCard();
        bankATM.enterPin();
        bankATM.checkBalance();
        bankATM.withdrawCash();
        bankATM.depositCash();
        bankATM.printReceipt();
        bankATM.ejectCard();
        bankATM.shutdown();
        Smartwatch watch = new FitnessWatch();
        watch.showTime();
        watch.trackSteps();
        watch.measureHeartRate();
        watch.startWorkout();
        watch.stopWorkout();
        watch.playMusic();
        watch.stopMusic();
        watch.showNotifications();
        watch.powerOff();

        FitnessWatch myWatch = new FitnessWatch();
        myWatch.showTime();
        myWatch.trackSteps();
        myWatch.measureHeartRate();
        myWatch.startWorkout();
        myWatch.stopWorkout();
        myWatch.playMusic();
        myWatch.stopMusic();
        myWatch.showNotifications();
        myWatch.powerOff();



    }
}
